name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Download antlr
      run: cd lib && wget "https://www.antlr.org/download/antlr-4.13.1-complete.jar"

    - name: Test build
      run: make all
