name: Release new compiler version source

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Download antlr
        run: cd lib && wget "https://www.antlr.org/download/antlr-4.13.1-complete.jar"

      - name: Test build
        run: make all

      - name: Clean up
        run: make clean && rm -rf lib/antlr-4.13.1-complete.jar && rm -rf .github/

      - name: Fix module info
        run: mv src/module-info.java src/module-info.java-orig && sed 's/requires org\.antlr\.antlr4\.runtime;/requires antlr;/' < src/module-info.java-orig > src/module-info.java && rm src/module-info.java-orig

      - name: Add original Makefile
        run: rm Makefile && mv Makefile.orig Makefile

      - name: Prepare for packaging
        run: mkdir "${GITHUB_WORKSPACE}/../lang24compiler" && mv * "${GITHUB_WORKSPACE}/../lang24compiler/" && mv "${GITHUB_WORKSPACE}/../lang24compiler/" "${GITHUB_WORKSPACE}"

      - name: Zip release
        run: zip -r compiler-release.zip lang24compiler

      - name: Upload release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: compiler-release.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
